// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ph-branding/BrandGuidelines.tsx": () => import("../components/mockups/ph-branding/BrandGuidelines.tsx"),
  "./components/mockups/ph-branding/BrandInAction.tsx": () => import("../components/mockups/ph-branding/BrandInAction.tsx"),
  "./components/mockups/ph-branding/ColorsTypography.tsx": () => import("../components/mockups/ph-branding/ColorsTypography.tsx"),
  "./components/mockups/ph-branding/LogoConcepts.tsx": () => import("../components/mockups/ph-branding/LogoConcepts.tsx")
};
